swagger: '2.0'
tags:
  - name: Cleansing CSV
get:
  description: None
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error
# Parameter untuk upload data
parameters:
  - name: file
    required: false
    in: formData
    type: file
